# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-09 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=1000)),
                ('Publish', models.BooleanField(default=False)),
                ('Content', models.TextField()),
                ('updateTime', models.DateTimeField(auto_now=True)),
                ('build', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
