# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='build',
            new_name='Build',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='updateTime',
            new_name='UpdateTime',
        ),
        migrations.AddField(
            model_name='article',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
