# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 02:48
from __future__ import unicode_literals

import article.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0003_auto_20180412_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='Image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=article.models.upload_location, width_field='width_field'),
        ),
    ]
