# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 23:24
from __future__ import unicode_literals

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20180412_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Image',
            field=models.ImageField(height_field='height_field', upload_to=article.models.upload_location, width_field='width_field'),
        ),
    ]
