# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-07 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20180422_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Tags', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TagsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
                ('Tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='Tags',
            field=models.ManyToManyField(through='article.TagsArticle', to='article.Tag'),
        ),
    ]
