# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-13 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20180507_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Counter',
            field=models.IntegerField(default=0),
        ),
    ]
