branch-defaults:
  default:
    environment: django-env
environment-defaults:
  django-env:
    branch: null
    repository: null
global:
  application_name: blog
  default_ec2_keyname: null
  default_platform: python-2.7
  default_region: ca-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
